# Generated by Django 4.2.9 on 2025-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='nome',
            field=models.CharField(max_length=140),
        ),
    ]
